### ISSUE TITLE
The AudioContext was not allowed to start.

### ISSUE THREAD

**Issue by abrambailey** [audiolabs/webMUSHRA#125]
I'm on Chrome Version 123.0.6312.123 (Official Build) (arm64) ... Getting the following when I try to access the default yaml file in chrome (localhost:8000) in the chrome console:

```
startup.js:171 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

MushraAudioControl.js:109 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at MushraAudioControl.convolve (MushraAudioControl.js:109:60)
    at MushraAudioControl.createLowerAnchor35 (MushraAudioControl.js:82:32)
    at new MushraAudioControl (MushraAudioControl.js:48:52)
    at MushraPage.init (MushraPage.js:70:29)
    at PageManager.start (PageManager.js:98:27)
    at callbackFilesLoaded (startup.js:34:15)
    at Object.<anonymous> (AudioFileLoader.js:49:11)
```

**Comment by abrambailey** [comment]
I noticed this related issue, but possibly a new fix is needed? https://github.com/audiolabs/webMUSHRA/issues/26

**Comment by abrambailey** [comment]
I was able to workaround this by setting createAnchor35 & createAnchor70 to false to get the demo running. Not sure what the issue was there.

**Comment by faroit** [comment]
@abrambailey what config are you running? can you send a url to reproduce?
